### ISSUE TITLE
0.72 Bug unable to save channel data

### ISSUE THREAD

**Issue by austinc-s** [labsyspharm/minerva_analysis#83]
1) Saving the channel data to database does not work on 0.72.  
Steps:  
- Make changes to channel intensity and color  
- Save to database  
- Load new sample  
- Load original sample again  
- Bug: Loading channel settings from database does not work, all settings back at default  

2) Saving the channel data to .csv does not work on 0.72.  
Steps:  
- Make changes to channel intensity and color  
- Error: 500 Internal Server Error results from trying to save channel data as a .csv  

System Info:  
Windows 11 build 22000.348  
Microsoft Edge (Chromium) 96.0.1054.43  
Data is log1p transformed upon import

**Comment by kruegert** [comment]
Ouch. Thanks. We will have a look.

**Comment by kruegert** [comment]
ERROR:minerva_analysis:Exception on /get_saved_channel_list [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "minerva_analysis\server\routes\data_routes.py", line 291, in get_saved_channel_list
    resp = data_model.get_saved_channel_list(datasource)
  File "minerva_analysis\server\models\data_model.py", line 610, in get_saved_channel_list
    return pickle.loads(channel_list.cells)
AttributeError: 'NoneType' object has no attribute 'cells'

**Comment by nchuynh** [comment]
Thanks Austin for reporting this issue and thanks Robert for info on the error.

There was a discrepancy in the channel names used for saving the data and uploading the data.  

We fixed this issue in the latest release (v0.73_gating), please let us know if you still have issues saving the channel data. Thanks!
